freeCodeCamp/classroom

- .gitpod.yml
This PR enables [Gitpod](https://gitpod.io) and sets up the workspaces to have preview builds, dependencies installed ahead of time, etc., and more. To test this you can click the "Open in Gitpod" button in the PR comments. 
It will set up a workspace with changes from the PR and have everything going.
> feat: create gitpod config

- mock-json-server/userdata.json
- package.json
This PR does the following:
- Installs json-server
- creates mock-json-server/userdata.json which has fake user data that is based off of: [certifiedUserData.js](https://github.com/freeCodeCamp/freeCodeCamp/blob/e0a5fcdb8eeffa53e7c6f07e182b21310f74da28/tools/scripts/seed/certifiedUserData.js)
To run the json server:
1.) `npm i`
2.) `npx json-server mock-json-server/userdata.json`
3.) navigate to `http://localhost:3000/user1`
Checklist:
Closes #XXXXX
> feat: create json-server

- pages/api/student_email_join.js
- pages/join/[...joinCode].js
Checklist:
On student join page: 
- Checks email if its associated with freeCodeCamp (mock API)
- Adds UUID to database instead of email
- Checks if its an invalid email (missing @ or empty) displays an alert message
- Checks if uuid is already in database (displays an alert if it is)
> Student api verification

- pages/classes/index.js
- pages/dashboard/[id].js
Checklist:
I also cleaned up the code a little while I was there.
> fix: use new fcc api endpoints

- .gitignore
- pages/api/create_class_teacher.js
- pages/api/deleteclass.js
- pages/api/modifyuser.js
- pages/api/student_email_join.js
> fix: Add authentication to APIs

- .env.sample
- README.md
- pages/api/auth/[...nextauth].js
Checklist:
Closes #144 
This PR adds NEXTAUTH_URL to sample env and to Nextauth config to make it easier for people using Gitpod to configure Nextauth. It also updates README.md with gitpod setup instructions.
Side note: when we deploy to production NEXTAUTH_URL will need to be changed to classroom.freecodecamp.org as well, so good to add it now anyways.
Made this PR in gitpod :)
> feat: Add NEXTAUTH_URL Config

- components/modal.js
- components/updateUserForm.js
- pages/api/create_class_teacher.js
> Fix issue 139, make consistent API endpoints. Also fixed API url for modifyuser

- .env.sample
- components/ClassInviteTable.js
> removed localhost:3000 from js files

- package.json
> fix: Pin the node and npm versions used by the Renovate bot

- README.md
- gitpod-instructions.sh
Co-authored-by: Qianru <qwei5@dons.usfca.edu>
Co-authored-by: Vanessa <vallevanessa13@gmail.com>
Checklist:
Closes #XXXXX
> Fix: Updated gitpod instructions and readme file.

- .env.sample
> Fix: update sampe.env with fake next auth secret

- pages/api/modifyuser.js
Co-authored-by: Shawn Templer <stemp001@ucr.edu>
Co-authored-by: Vanessa Valle <vallevanessa13@gmail.com>
Checklist:
Closes #202
> fix: Prevent ADMIN roles to be changed to non-ADMIN roles

- pages/admin/actions/[id].js
- pages/admin/index.js
Co-authored-by: Shawn Templer <stemp001@ucr.edu>
Co-authored-by: Qianru Wei <qwei5@dons.usfca.edu>
Checklist:
Closes #218
> Fix:  Admins are able to sign out and return to the home page.

- package-lock.json
- package.json
> feat: add jest

- README.md
> fix: Add DATABASE_URL instructions for Docker

- mock-json-server/fccdata.json
> Fix: Removed errors from fccdata so dashboard v1 works

- pages/dashboard/v2/[id].js
> Feat: Check if user ID matches the classroom teacher ID in v2 dashboard

- components/ClassInviteTable.js
- components/authButton.js
- components/modal.js
- components/navbar.js
- components/updateUserForm.js
- pages/index.js
- pages/join/[...joinCode].js
- styles/globals.css
- tailwind.config.js
I have added colors variables to the tailwind.config.js file, now we can access the values without having to hardcode them each time. We can still have all the screen sizes, font sizes etc there but we will begin by colors only. I thought this could be a right fix. I will appericiate any review on this.
Todos:
#292
Checklist:
> refactor(code-refactor): :sparkles: Refactored code to resolve #292 issue

- README.md
I have added a section in readme.md that recomends using propoer style guild to meet FreeCodeCamp brand's identity.
Checklist:
Closes #259
> docs: :zap: Adding style guide to readme.md

- __tests__/components/__snapshots__/navbar.test.jsx.snap
- __tests__/components/navbar.test.jsx
- package-lock.json
- package.json
> feat: add first snapshot test for navbar

- README.md
Checklist:
Closes #383
Relates to https://github.com/freeCodeCamp/classroom/pull/349 and https://github.com/freeCodeCamp/classroom/issues/355
> docs(readme.md): add GitHub Codespaces

- README.md
Checklist:
Closes #378
Co-authored-by: Natalia Gill <sngill.ca@gmail.com>
> docs(readme.md): add tips

- README.md
Checklist:
Closes #372
Co-authored-by: Natalia Gill <ngillux@gmail.com>
Co-authored-by: Lloyd Chang <lloydchang@gmail.com>
> (docs): System diagram added with canva link

- .github/workflows/update-license.yaml
> ci(update-license.yaml): add automation to change copyright years

- .devcontainer/devcontainer.json
> build(devcontainer.json): add VS Code Live Share

- util/api_proccesor.js
Checklist:
Due to sync overlap, allChallenges was not updated, this pull request accounts for updating it back.
> Adding allChallenges attribute after async merge overwrite
